"""Review summary composition for the GitHub PR review body.

Implements Section 3.6.2 of the architecture document:
- Findings breakdown by severity.
- Summary metrics (files analyzed, analysis duration, OWASP categories).
- Truncation notice when comments exceed the 256 limit.
- Collapsible methodology disclosure.
- Summary list of any findings located outside diff hunks.
"""

from __future__ import annotations

from collections import Counter
from typing import Sequence

from codepulse.aggregation.models import DeduplicationResult, Finding


def compose_review_summary(
    dedup_result: DeduplicationResult,
    files_analyzed: int = 1,
    analysis_duration_ms: int = 0,
    model_version: str = "gemini-3.7-flash",
    unmapped_findings: Sequence[Finding] | None = None,
) -> str:
    """Compose top-level markdown summary for GitHub review body.

    Args:
        dedup_result: Result from deduplicate_and_sort.
        files_analyzed: Count of files analyzed in PR.
        analysis_duration_ms: Total pipeline duration in milliseconds.
        model_version: Gemini model version used for LLM analysis.
        unmapped_findings: Findings that could not be placed inline on diff.

    Returns:
        Markdown string for GitHub review body.
    """
    findings = dedup_result.findings
    counts = Counter(f.severity.lower() for f in findings)
    critical = counts.get("critical", 0)
    high = counts.get("high", 0)
    medium = counts.get("medium", 0)
    low = counts.get("low", 0)

    total_findings = len(findings)

    # Title & Badge Bar
    parts = [
        "## 🛡️ CodePulse AI Security & Quality Review",
        "",
    ]

    if total_findings == 0:
        parts.extend([
            "✅ **No security vulnerabilities or memory leaks detected in modified code.**",
            "",
        ])
    else:
        badge_line = (
            f"🔴 **Critical:** {critical} | "
            f"🟠 **High:** {high} | "
            f"🟡 **Medium:** {medium} | "
            f"🔵 **Low:** {low}"
        )
        parts.extend([
            badge_line,
            "",
        ])

    # Truncation alert
    if dedup_result.truncated_count > 0:
        parts.extend([
            f"> ⚠️ **Notice:** {dedup_result.truncated_count} lower-severity findings were "
            f"omitted to respect GitHub's 256-comment review limit. Critical and high-severity "
            f"findings were prioritized.",
            "",
        ])

    # Analysis Overview Table
    duration_sec = analysis_duration_ms / 1000.0 if analysis_duration_ms else 0.0
    category_counts = Counter(f.category for f in findings)
    categories_str = ", ".join(f"`{c}` ({cnt})" for c, cnt in category_counts.most_common()) or "None"

    parts.extend([
        "### 📊 Analysis Overview",
        "",
        "| Metric | Value |",
        "| --- | --- |",
        f"| **Files Analyzed** | {files_analyzed} |",
        f"| **Total Findings** | {total_findings} |",
        f"| **Categories Detected** | {categories_str} |",
        f"| **Duration** | {duration_sec:.2f}s |",
        "",
    ])

    # Unmapped Findings (outside diff hunks)
    if unmapped_findings:
        parts.extend([
            "### 📌 Additional Findings (Outside Changed Lines)",
            "",
            "The following issues were identified in related file regions outside current diff hunks:",
            "",
        ])
        for uf in unmapped_findings:
            parts.append(
                f"- **[{uf.severity.upper()}]** `{uf.category}` in `{uf.file_path}:{uf.line_start}`: "
                f"{uf.title} — {uf.explanation.splitlines()[0]}"
            )
        parts.append("")

    # Methodology Disclosure
    parts.extend([
        "<details>",
        "<summary>🔬 Methodology & Audit Disclosure</summary>",
        "",
        "This audit was generated by CodePulse AI using a dual-analysis pipeline:",
        "1. **AST Heuristics Engine:** Tree-sitter static analysis detecting OWASP Top 10 and memory-leak patterns.",
        f"2. **LLM Engine:** Multi-chunk reasoning via Google `{model_version}` with structured outputs and prompt injection defenses (§3.4.7).",
        "3. **Deduplication:** Automatic confidence-weighted merge across overlapping AST and LLM detections.",
        "",
        "*Event type:* `COMMENT` (non-blocking review feedback).",
        "</details>",
    ])

    return "\n".join(parts)
